############
# settings #
############
# prezto
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# fzf
source <(fzf --zsh)

# tmux
if [ -z $TMUX ]; then
  tmuximum
fi

eval "$(~/.local/bin/mise activate zsh)"

# emacs
[[ $EMACS = t ]] && unsetopt zle

# OPAM configuration
. $HOME/.opam/opam-init/init.zsh >/dev/null 2>/dev/null || true

# Rust
source ~/.cargo/env

# Haskell
[ -f "/home/okkey/.ghcup/env" ] && source "/home/okkey/.ghcup/env" # ghcup-env

# added by travis gem
[ -f $HOME/.travis/travis.sh ] && source $HOME/.travis/travis.sh

# The next line updates PATH for the Google Cloud SDK.
if [ -f "$HOME/google-cloud-sdk/path.zsh.inc" ]; then . "$HOME/google-cloud-sdk/path.zsh.inc"; fi

# The next line enables shell command completion for gcloud.
if [ -f "$HOME/google-cloud-sdk/completion.zsh.inc" ]; then . "$HOME/google-cloud-sdk/completion.zsh.inc"; fi

################
# key bindings #
################
bindkey '^L' forward-char
bindkey '^H' backward-char
bindkey '^K' kill-line
bindkey '^Y' kill-line
bindkey '^V' yank
bindkey '^B' backward-delete-char

function rs() {
  # read name
  NAME=$(basename $(pwd))
  rename-session ${NAME/./}
  zle reset-prompt
}
zle -N rs
bindkey '^S' rs

function guake-new-tab() {
  guake -n 0
}
zle -N guake-new-tab
bindkey '^T' guake-new-tab

#######################
# aliases (functions) #
#######################
### System ###
alias arch='uname -m'

### Shell ###
alias zrc='source ~/.zshrc'
alias zenv='source ~/.zshenv'
alias z='zrc && zenv'

### Tools ###
alias clip='xclip -selection clipboard -in'
alias pcp=clip
alias tls='tmux ls'
alias xmod='xmodmap ~/.Xmodmap'

function to-lower() {
  echo -n $@ | tr "[:upper:]" "[:lower:]" | pcp
}

function to-upper() {
  echo -n $@ | tr "[:lower:]" "[:upper:]" | pcp
}

function to-snake() {
  echo -n $@ | sed -E 's/(.)([A-Z])/\1_\2/g' | tr '[A-Z]' '[a-z]'
}

function to-pascal() {
  echo -n $@ | awk -F '_' '{ for (i = 1; i <= NF; i++) { printf toupper(substr($i, 1, 1)) substr($i, 2) } }'
}

function gen-random-graph() {
  more /dev/urandom  | tr -d -c '[:graph:]' | fold -w $@ | head -n 1
}

function gen-random-alnum() {
  more /dev/urandom  | tr -d -c '[:alnum:]' | fold -w $@ | head -n 1
}

### Files ###
alias ll='ls -lhF'
alias la='ls -lahF'
alias clear-trash='sudo rm -rf $TRASH/files/* && sudo rm -rf $TRASH/info/*'
function rmrf() {
  mv -vuf $@ $TRASH/files/
}
function count-lines() {
  cat $@ | wc -l
}
function ffind() {
  find ./ -type f -print | xargs grep $@
}

### Editor ###
function code-open-directory-or-workspace() {
  workspace_file=$(find . -maxdepth 1 -name "*.code-workspace" | head -n 1)

  if [[ -n "$workspace_file" ]]; then
    echo "Open workspace: $workspace_file"
    code "$workspace_file"
  else
    echo "Open directory: $(pwd)"
    code .
  fi
}

alias c='code-open-directory-or-workspace'

### Stack (Haskell) ###
alias se='stack exec'
function se2() {
  app=${PWD##*/}
  stack exec $app $@
}
alias sg='stack ghci'
alias sb='stack build'

### Git ###
alias ga='git add'
alias gb='git branch'
alias gba='git branch --all'
alias gbr='git branch --remote'
alias gbvv='git branch -vv'
alias gci='git commit --allow-empty -m "Initial commit"'
alias initial-commit='gci'
alias git-current-branch='git symbolic-ref --short HEAD'
alias gcb='git-current-branch'
alias gcl='git clone'
alias gcm='git commit -m'
alias gd='git diff'
alias gf='git fetch'
alias gl='git log'
alias gln='git log -n'
alias glo='git log --oneline'
alias glon='git log --oneline -n'
alias gm='git merge'
alias gp='git push'
alias gpu='git push -u'
alias gpuo='git push -u origin'
alias gpl='git pull'
alias gs='git status'
alias gsw='git switch'
alias grs='git restore'
alias grsw='git restore --worktree'
alias gfp='git fetch --prune'
alias gwip='git add . && git commit -m "[wip]"'

function gmp() {
  current_branch=$(git symbolic-ref --short HEAD)

  git switch $@ &&
    git merge $current_branch &&
    git push &&
    git switch $current_branch
}

function gpc() {
  current_branch=$(git symbolic-ref --short HEAD)
  git push -u origin $current_branch
}

function git-new-branch-from-origin() {
  git switch -c $@ origin/$@
}

function git-latest-commit-hash() {
  git log --oneline -n 1 | awk '{print $1}'
}

function git-create-branch-and-push() {
  git switch -c $@
  git push -u origin $@
}

function git-create-feature-branch-and-push() {
  git-create-branch-and-push feature/$@
}

### Math ###
function mathrm() {
  rmrf $@*.css_log $@*.hs $@*.tc-log $@*.xml
}
alias updateOEIS='rm -rf .stack-workd/downloaded/ && stack build'

### Ruby ###
alias bundle inatall='bundle install --path=vendor/bundle'

### AWS ###
alias acl='aws configure list'

function aws-start-proxy() {
  region=us-east-1

  aws ec2 start-instances --region $region --instance-ids $@ &&
    aws ec2 wait instance-status-ok --region $region --instance-ids $@ &&
    aws ec2 describe-instances --region $region --instance-ids $@
}

function aws-stop-proxy() {
  region=us-east-1

  aws ec2 stop-instances --region $region --instance-ids $@ &&
    aws ec2 describe-instances --region $region --instance-ids $@
}

# AWS
function aws-connect-instance () {
  instance_id=$1
  profile=$2

  aws ec2 start-instances --instance-ids $instance_id --profile $profile

  echo 'waiting...'
  aws ec2 wait instance-status-ok --instance-ids $instance_id --profile $profile

  aws ssm start-session --target $instance_id --profile $profile
}

### Docker ###
alias dokcer='docker'
alias docker-compose='/usr/lib/docker/cli-plugins/docker-compose compose'
alias docker-rm-all='docker rm $(docker ps -a -q)'
alias docker-rmi-all='docker rmi $(docker images -q)'
alias dps='docker ps -a'
alias dmg='docker images'

### Claude Code ###
claude-ask() {
  echo "[Claude Code] Continue previous session? [Y/n]"
  read "answer?> "

  if [[ ${answer:l} =~ ^(n|no)$ ]]; then
    echo '==== Start new session ===='
    claude
  else
    echo '==== Continue ===='
    claude --continue
  fi
}

alias ca='claude-ask'

### Others ###
alias hcurl='curl -D - -s  -o /dev/null'
alias openapi-generator='openapi-generator-cli'

### Load local zshrc ###
[ -f ~/.zshrc.local ] && source ~/.zshrc.local
