# prezto
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
   source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# tmux
if [ -z $TMUX ]; then
  tmuximum
fi

# emacs
[[ $EMACS = t ]] && unsetopt zle

# OPAM configuration
. /home/okkey/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

# key binding
bindkey '^L' forward-char
bindkey '^F' forward-char
bindkey '^H' backward-char
bindkey '^B' backward-char
bindkey '^K' kill-line
bindkey '^Y' yank
bindkey '^V' yank


# alias
alias sz='source ~/.zshrc'
alias la='ls -la'
alias pcp='xclip -selection clipboard -in'
alias tls='tmux ls'
alias rmtrash='sudo rm -rf ~/.local/share/Trash/expunged/* ~/.local/share/Trash/info/*'

funciton mvtrash (){
  mv $@ ~/.local/share/Trash/expunged/
}
alias mathrm='mvtrash *.css_log *.hs *.tc-log *.xml'

function count-lines(){
  cat $@ | wc -l
}

alias vi='emacs -nw'
alias mikutter='ruby ~/mikutter/mikutter.rb'
alias xmod='xmodmap ~/.Xmodmap'
alias emacs='emacs-snapshot'


alias se='stack exec'
function se2(){
  app=${PWD##*/}
  stack exec $app $@
}
alias sg='stack ghci'
alias sb='stack build'

alias ga='git add'
alias gs='git status'
alias gcm='git commit -m'

alias mark='mkdir student-reports && mv ./201******-*.nb ./student-reports && cd ./student-reports && rename s/.nb/-okkey.nb/g ./201******-*.nb'


# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/okkey/src/google-cloud-sdk/path.zsh.inc' ]; then source '/home/okkey/src/google-cloud-sdk/path.zsh.inc'; fi


# The next line enables shell command completion for gcloud.
if [ -f '/home/okkey/src/google-cloud-sdk/completion.zsh.inc' ]; then source '/home/okkey/src/google-cloud-sdk/completion.zsh.inc'; fi
